services:
  - type: web
    name: sistema-alumnos-artes-marciales
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: alumnos-db
          property: connectionString

databases:
  - name: alumnos-db
    databaseName: alumnos_db
    user: alumnos_user
